### ISSUE TITLE
Allow explicit integer size

### ISSUE THREAD

**Issue by naquad** [robmorgan/phinx#501] opened 2015-02-23 14:28 UTC
`int(4)` - can't be done with Phinx, please add `size` / `length` to `integer`

**Comment by shadowhand** [comment] 2015-02-23 16:05
Isn't this a duplicate of #493?

**Comment by naquad** [comment] 2015-02-23 16:20
I've tried with `limit`:

```
->addColumn('opacity', 'integer', array('null' => true, 'limit' => 3))
```

result:

```
`opacity` int(11) DEFAULT NULL,
```

**Comment by shadowhand** [comment] 2015-02-23 16:30
Yes that is the same as #493.

**Closed by shadowhand** 2015-02-23 16:30 UTC
Labels: bug

**Comment by naquad** [comment] 2015-02-23 16:33
Any hint on when will that be released?

**Comment by shadowhand** [comment] 2015-02-23 16:43
Just released v0.4.3! https://phinx.org/

**Comment by naquad** [comment] 2015-02-23 16:55
Thank you! That fixed the problem.

**Comment by zdenekgebauer** [comment] 2015-08-02 08:49
there is also small bug with length of signed/unsigned columns, ie:
->addColumn('bar_id', 'integer', array('limit' => MysqlAdapter::INT_REGULAR, 'signed' => false))
create
`bar_id` int(11) unsigned NOT NULL,
but it should create 
`bar_id` int(10) unsigned NOT NULL,
