### ISSUE TITLE
Duplicate Names

### ISSUE THREAD

**Issue by daniel-lang** [robmorgan/phinx#473] opened 2015-02-05 10:54 UTC
When creating a second migrations with the same name. Like `phinx create Test`  and running the same command again will work. But commans like `status` will output an error: 
```
[InvalidArgumentException]
Migration "20150205104723_test.php" has the same name as "20150130090329_test.php"
```

A check when creating the migrations would be great.

**Comment by shadowhand** [comment] 2015-02-05 14:13
Duplicate of #362.

**Comment by daniel-lang** [comment] 2015-02-05 14:17
#362 is about duplicate timestamps when creating two migrations at once. I'm addressing the problem of creating a second migration with the same name.

In my opinion, these are two different problems.

**Comment by robmorgan** [comment] 2015-09-02 11:11
@daniel-lang they are indeed two different problems.

**Closed** 2015-09-02 11:12 UTC
