### ISSUE TITLE
Track seeds

### ISSUE THREAD

**Issue by nickcv-ln** [robmorgan/phinx#981] opened 2016-11-16 11:05 UTC
Phinx keeps track of which migration were run before, but it does not do the same for seeds.
Tracking them would avoid reseeding the same table more than once.

In the same way it would be nice to be able to have the seed `ensure` that data is present:

i.e.
with a list of records the seed should create it only if the record does not currently exists.

Without either feature if you try to reseed a record that is setting a unique key you will get errors.

**Comment by robmorgan** [comment] 2016-11-16 12:01
Hi @nickcv-ln 

In general if you want a guarantee that something only happens once then I'd recommend a migration as they are tracked etc and can also insert data.

If you want to create ensure behaviour using seeders then I'd recommend to use the standard SQL methods available in seeders and detect if rows are present before inserting them. Seeders are dumb by design and are supposed to run repeatably.

You can avoid duplicate keys by using libraries like Faker to ensure unique data is inserted.

I'm closing this for now.

- R

**Closed by robmorgan** 2016-11-16 12:01 UTC
