### ISSUE TITLE
Multiple migration paths

### ISSUE THREAD

**Issue by aimfeld** [robmorgan/phinx#232] opened 2014-04-25 10:50 UTC
We develop a framework which we include as a module in several projects. Both the framework and the projects contain phinx migrations. 

Is there a way I can set up two (or more) migration paths in phinx.yml (one for framework migrations and one for project-specific migrations), so phinx looks in both paths for migrations? If not, it would be a great feature! The [documentation](http://docs.phinx.org/en/latest/configuration.html#migration-path) talks about a "migration path" (singular) which implies that only one path can be specified.

It would be important that migrations are run in the sequence of the timestamps in the migration file names (as oposed to running all framework migrations and then project-specific migrations. 

Here's an example of what I'd like to do, where migrations 1-4 are run in sequence:
phinx.yml (specify two paths, e.g. separated with semicolon)

```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/migrations;%%PHINX_CONFIG_DIR%%/vendor/our-company/our-framework/migrations
```

```
./migrations
    20130101000000_migration_1.php
    20130103000000_migration_3.php
./vendor/our-company/our-framework/migrations
    20130102000000_migration_2.php
    20130104000000_migration_4.php
```

**Comment by markushausammann** [comment] 2015-09-08 09:06
Has this been solved in the meantime?

**Comment by GodLesZ** [comment] 2016-02-16 08:32
Also starring hard to this, any chance to get this @robmorgan ?

**Comment by dzubchik** [comment] 2016-02-27 17:38
@robmorgan , what is the status of this feature?

**Comment by Swader** [comment] 2016-05-07 08:18
Ping @robmorgan.
High demand. Any feedback for us whatsoever?

**Comment by aimfeld** [comment] 2016-05-07 10:28
As I couldn't wait for this feature, I have implemented a workaround. I just copy all migration files from different paths into a single migrations directory during the deployment process. It's quite easy and works well for us.

**Comment by michanismus** [comment] 2016-05-08 13:45
I wrote a little helper. Script loads app config (Horus\Config) and creates a Phinx config each time it is called.
It's just my workaround but I am very happy. The creation of migrations is no pain anymore and it looks for migrations in all my bundle paths. Just take a look at the script...

```php
#!/usr/bin/env php
<?php
$root = dirname(__DIR__);
require_once $root . '/vendor/autoload.php';

use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Phinx\Console\PhinxApplication;
use Phinx\Config\Config as PConfig;
use Horus\Config;

$dispatcher = new EventDispatcher();
$dispatcher->addListener(ConsoleEvents::COMMAND, function (ConsoleCommandEvent $event) use ($root) {

    $command = $event->getCommand();
    if ($command instanceof Phinx\Console\Command\AbstractCommand) {

        $input       = $event->getInput();
        $output      = $event->getOutput();
        $environment = 'development';

        if ($input->hasOption('environment')) {
            if (null !== $input->getOption('environment')) {
                $environment = $input->getOption('environment');
            } else {
                $input->setOption('environment', $environment);
            }
        }

        $config = Config::load($root . '/app/config/config_' . $environment . '.yml');

        if (empty($config->toArray())) {
            $output->writeln(sprintf('<error>Unknown environment "%s"</error>', $environment));
            exit;
        }

        switch (get_class($command)) {
            case 'Phinx\Console\Command\Create':
            case 'Phinx\Console\Command\SeedCreate':
                $migrations = 'Resources/migrations';
                $seeds      = 'Resources/migrations/seeds';
                break;
            default:
                $migrations = $root . '/src/*/*/Resources/migrations';
                $seeds      = $root . '/src/*/*/Resources/migrations/seeds';
        }

        $config = new PConfig([
                'environments' => [
                    'default_migration_table' => 'phinxlog',
                    'default_database'        => $environment,
                    $environment              => [
                        'adapter'  => 'mysql',
                        'host'     => $config->database->host,
                        'name'     => $config->database->dbname,
                        'user'     => $config->database->username,
                        'pass'     => $config->database->password,
                        'port'     => 3306,
                        'charset'  => 'utf8'
                    ]
                ],
                'paths' => [
                    'migrations' => $migrations,
                    'seeds'      => $seeds
                ],
            ]);

        $command->setConfig($config);
    }
});

$phinx = new Phinx\Console\PhinxApplication();
$phinx->setDispatcher($dispatcher);
$phinx->run();
```

**Comment by janreges** [comment] 2016-05-24 10:49
Hi... It works!

Setup your variable ``paths.migrations`` like this:

```{/path/to/my-project/db/migrations,/path/to/my-project/vendor/*/*/db/migrations}```

So, multiple directories with wildcard expansion in curly brackets, delimited by comma.

I hope, it helps :)

**Comment by jaroslavrehorka** [comment] 2016-06-16 15:13
+1

**Comment by rogoit** [comment] 2016-09-01 15:57
Yes the problem is the creating and to get the timestamp in the file name

**Comment by karborator** [comment] 2017-01-11 08:36
👍

**Comment by ricco24** [comment] 2017-03-27 14:09
Look at this https://github.com/lulco/phoenix. Syntax is very similar to phinx but has this feature implemnted already.

**Comment by t-moennich** [comment] 2017-03-28 05:21
fyi this is possible since 0.7.0 but Unfortunately it wasn't mentioned in the release notes.. ;)

https://github.com/robmorgan/phinx/blob/v0.7.0/tests/Phinx/Config/_files/valid_config.php

**Comment by rquadling** [comment] 2017-04-04 12:41
Confirmed. This feature was initially part of the 0.7 dev branch (https://github.com/robmorgan/phinx/pull/1022/commits/28d9afb01175704062277c5365f610a08fed21d4) It was merged as part of merging the dev branches into master.

Sorry for the lack of release notes.

**Closed by rquadling** 2017-04-04 12:41 UTC
Labels: feature
